### ISSUE TITLE
how the annotation_TSS is made

### ISSUE THREAD

**Issue by crazyhottommy** [qinqian/histonerp#1]
Hi Alvin,
Thanks for pointing me to this repo! I heard you met my current boss Steven at the Broad Depmap conference. Small world!

I have a question on how the annotation_TSS file is made.

```
chr1    11873   11874   NR_046018:DDX11L1       0       +
chr1    17436   17437   NR_107063:MIR6859-3     0       -
chr1    17436   17437   NR_128720:MIR6859-4     0       -
```
It looks like you are using RefSeq transcripts.  Given a single gene has multiple transcripts, how did you handle it?

Thanks!
Hope all is well at Broad.

Tommy

**Comment by qinqian** [comment]
Hi Tommy, 

Yes, I met Steven in person at Broad. What a small world!

We are using UCSC RefSeq transcripts annotation, for a gene with multiple transcripts, we combine the ref_seq_id with gene symbol on the column four, e.g. NR_046018:DDX11L1.  That means we treated each individual transcripts and its TSS as an independent records. For downstream analysis such as gene set analysis, we de-duplicate the transcripts based on the gene symbol to avoid the overfitting of a gene set. 

Best,
Alvin

**Comment by qinqian** [comment]
The script to generate this annotation file from RefSeq is available here (https://github.com/qinqian/histonerp/blob/main/test/get_tss.sh)

**Comment by crazyhottommy** [comment]
thanks!! @qinqian what's your email? Would you happen to have 30 minutes to catch up on a Teams or Zoom call? I am interested in what you are doing and would like to see if we can share some experience. my email is tangming2005atgmail.com
